### ISSUE TITLE
intent.extras must not be null

### ISSUE THREAD

**Issue by Jonty800** [pusher/push-notifications-android#105]
We're experiencing several reports of a crash in our Crashlytics logs.

Do you know what might be causing this issue?

<img width="1402" alt="Screenshot 2020-03-09 at 16 12 54" src="https://user-images.githubusercontent.com/1188837/76234174-45a36380-6221-11ea-9880-9394b853e9ba.png">

**Comment by Jonty800** [comment]
This issue affects many users. Are there any plans to fix this??

**Comment by daniellevass** [comment]
Hi, 

Can you check you are using the latest version of the beams SDK - currently version 1.6.2? 

I believe this issue was [fixed with release 1.6.1](https://github.com/pusher/push-notifications-android/blob/master/CHANGELOG.md#161---2020-01-27)

I am closing this issue but please re-open if you're still experiencing this.

Thank you,

Danielle.

**Comment by Jonty800** [comment]
Yes, we have been using 1.6.2 for some time now and this issue still exists
